name: CI
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: score-spec/setup-score@v2
        with:
          file: score-compose
          version: 0.15.6
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: score-compose init
      - run: score-compose generate score.yaml --build=web=.
      - run: docker compose up -d
      - run: curl http://$(score-compose resources get-outputs 'dns.default#hello-world.example-dns' --format '{{.host}}'):8080 -v | tee | grep 'Score Example'
    outputs:
      version: ${{ steps.semver.outputs.version }}
  
  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: score-spec/setup-score@v2
        with:
          file: score-k8s
          version: 0.1.5
          token: ${{ secrets.GITHUB_TOKEN }}
