name: CI
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: paulhatch/semantic-version@v5.0.3
        id: semver
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs:
      version: ${{ steps.semver.outputs.version }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: score-spec/setup-score@v2
        with:
          file: score-compose
          version: latest